sonar.projectKey=reactsonaractions
sonar.projectName=reactsonaractions

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.exclusions=node_modules/**,dist/**,build/**